# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

variables:
  LT_USERNAME: 'varunkumarb'
  LT_ACCESS_KEY: 'LT_KKkSe0kYnq4nzjNBLJmk0c1HSo1PUWtH7exYP8zVemT6dyw'
  LT_BUILD_NAME: 'Azure_testng_demo'

steps:
- task: configuration@1
  inputs:
    connection: 'tunnelVarun'
    isTunnelActivate: true
    tunnelOptions: '{"verbose": true, "logfile": "a.log", "loglevel": "debug"}'
    isAppAutomate: false
    isSmartUI: false

- script: mvn test -P single
  displayName: 'Run Tests'
  env:
    LT_USERNAME: $(LT_USERNAME)
    LT_ACCESS_KEY: $(LT_ACCESS_KEY)
    LT_BUILD_NAME: $(LT_BUILD_NAME)

- task: LambdatestResults@1
  displayName: 'LambdaTest Results'

- task: stoptunnel@1
  displayName: 'Stop Tunnel'

- script: |
    copy a.log "$(Build.ArtifactStagingDirectory)\a.log"
  displayName: 'Copy a.log to ArtifactStagingDirectory'
  condition: always()

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publish Artifact: a.log'
  condition: always()
  continueOnError: true
  retryCountOnTaskFailure: 1
