# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'


variables:
  LT_USERNAME: 'varunkumarb'
  LT_ACCESS_KEY: 'LT_KKkSe0kYnq4nzjNBLJmk0c1HSo1PUWtH7exYP8zVemT6dyw'
  LT_BUILD_NAME: 'Azure_testng_demo'

# Maven
steps:
- task: configuration@1
  inputs:
    connection: 'tunnelVarun'
    isTunnelActivate: true
    tunnelOptions: '{"verbose": true, "logfile": "a.log", "loglevel": "debug"}'
    isAppAutomate: false
    isSmartUI: false

- script: |
    echo Executing curl upload...
    curl -vvv lambdatest.com
  displayName: 'Checking accessibility of the application'

- script: mvn test -P single
  displayName: 'Run Tests'

- task: LambdatestResults@1

- task: stoptunnel@1

- script: |
   copy a.log $(Build.ArtifactStagingDirectory)\a.log
  displayName: 'Command Line Script'
  condition: always()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  continueOnError: true
  condition: always()
  retryCountOnTaskFailure: 1